import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import ReactTyped from "react-typed";

const Home = () => {
  return (
    <Layout page={"Home"}>
      <div className={styles.container}>
        <Head>
          <title>Rishabh's Portflio - Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Hello, this is{" "}
            <a
              href="https://rishabhpathak.netlify.app/"
              target="_blank"
              // className="michroma"
            >
              <ReactTyped
                strings={["Rishabh Pathak"]}
                typeSpeed={60}
                // smartBackspace={true}
                // backSpeed={60}
                showCursor={false}
                // loop
              />
            </a>
          </h1>
        </main>
      </div>
    </Layout>
  );
};

export default Home;
